name: PHPUnit tests

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      uses: php-actions/composer@v2
      
    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist

    - name: Run test suite
      run: composer cat
