name: PHPUnit tests

on:
  push:
    branches: [ master ]

jobs:
  build-and-run-tests:
    runs-on: self-hosted
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      
    - name: "Run tests"
      uses: php-actions/composer@v2
      with:
        command: composer install && composer cat
 
