name: PHPUnit tests

on:
  push:
    branches: [ master ]

jobs:
  build-and-run-tests:
    runs-on: self-hosted
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      
    - name: Install dependencies
      uses: php-actions/composer@v2
      
    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Run test suite
      run: composer cat
